=encoding utf-8

=head1 NAME

Ark::Manual - Ark Documentation

=head1 はじめの一歩

=over 4

=item *

L<概要 - Ark とは|Ark::Manual::About>

=item *

L<インストール|Ark::Manual::Install>

=back

=head1 チュートリアル

=over 4

=item *

L<Hello World アプリケーション|Ark::Manual::Tutorial::HelloWorld>

=item *

テンプレートを使う

=item *

データベースを使う

=item *

ユーザー認証

=item *

OpenID 認証

=item *

アプリケーションのテスト

=item *

共有サーバーへのデプロイ

=back

=head1 ドキュメント

=head2 コア

=over 4

=item *

L<Ark の基本|Ark::Manual::ArkBasics>

=item *

L<Controller と Action|Ark::Manual::ControllerAction>

=item *

Model と View

=item *

L<ヘルパースクリプト|Ark::Manual::ark>

=back

=head2 プラグイン

=over 4

=item *

セッション

=item *

キャッシュ

=item *

認証

=back

=head1 AUTHOR

Daisuke Murase <typester@cpan.org>

=head1 COPYRIGHT & LICENSE

Copyright (c) 2009 KAYAC Inc. All rights reserved.

This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

The full text of the license can be found in the LICENSE file included with this module.

=cut


